# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
resources:
  repositories:
  - repository: myfirstpipeline
    type: github
    name: SaiBhargav-M/myfirstpipeline
    endpoint: SaiBhargav-M
    ref: main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: myfirstpipeline

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'myfirstpipelines'
    subscriptionId: '4152d77a-784e-4df1-bd82-0e04268e7073'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'https://github.com/SaiBhargav-M/myfirstpipeline/blob/master/arm.json'
    deploymentMode: 'Incremental'
    deploymentName: 'deploy resource group rg4'
