# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none # Disable CI triggers.
pr: none # Disable pr.

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

jobs:
  - job: job1
    steps:    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'myfirstpipelines'
        subscriptionId: '4152d77a-784e-4df1-bd82-0e04268e7073'
        location: 'East US 2'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/SaiBhargav-M/myfirstpipeline/master/arm.json'
        deploymentMode: 'Incremental'
        deploymentName: 'rg6'
  - job: job2
    dependsOn: job1
    condition: succeeded()
    steps:        
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'myfirstpipelines'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'sleep 120'
  - job: job3
    dependsOn: job2
    condition: succeeded()
    steps:        
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'myfirstpipelines'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group delete -n rg6 --yes'

